sudo: required

services:
  - docker

language: python
python:
  - "3.5"
  - "3.6"
branches:
 only:
 #- master
 #- dev
 - ci

before_install:
 - pip install pytest-cov
 - docker build -f docker/Dockerfile -t openbread_docker docker

script:
 - docker run --rm \
        -v $(pwd)/work:/home/user/work \
        -v $(pwd)/..:/openbread \
        openbread_docker 	\
        py.test --cov=./ /openbread/test

after_success:
- pip install codecov; codecov;