FROM danielweilandt/openbread_docker:latest
ENTRYPOINT []
USER root
RUN mkdir /openbread
COPY . /openbread
USER user
RUN pip install --user pytest-cov
RUN pip install --user --global-option=build_ext /openbread
CMD /bin/bash