FROM danielweilandt/openbread_docker:latest
ENTRYPOINT []
USER root
RUN mkdir /openbread
COPY . /openbread
RUN chown -R user /openbread
User user
RUN pip install --user pytest-cov
RUN /bin/bash -c "source /home/user/openfpm_vars && pip install --user -e /openbread"
CMD /bin/bash